// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VillaAgency.Data;

#nullable disable

namespace VillaAgency.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260216141243_AdminHashed")]
    partial class AdminHashed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", "app");

                    b.HasData(
                        new
                        {
                            Id = "019c330e-6c3e-7ace-aa53-1dfe8fda644f",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "019c330e-6c3e-753c-bd9b-7e2e7ad57c19",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "app");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "app");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "app");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "app");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "app");
                });

            modelBuilder.Entity("VillaAgency.Models.Entities.AppilcationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastLogin")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", "app");
                });

            modelBuilder.Entity("VillaAgency.Models.Entities.Banner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LinkedinUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Tittle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Banners", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3d4e5f6-3333-3333-3333-000000000001"),
                            Category = "Toronto, Canada",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Discover the finest villas in the heart of Toronto with stunning architecture and modern amenities.",
                            DisplayOrder = 1,
                            ImageUrl = "/assets/images/banner-01.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            LinkedinUrl = "#",
                            Tittle = "Hurry! Get the Best Villa for you"
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-3333-3333-3333-000000000002"),
                            Category = "Melbourne, Australia",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Explore premium villa options in Melbourne with world-class facilities.",
                            DisplayOrder = 2,
                            ImageUrl = "/assets/images/banner-02.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            LinkedinUrl = "#",
                            Tittle = "Be Quick! Get the best villa in town"
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-3333-3333-3333-000000000003"),
                            Category = "Miami, South Florida",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Exclusive penthouses in Miami offering breathtaking ocean views.",
                            DisplayOrder = 3,
                            ImageUrl = "/assets/images/banner-03.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            LinkedinUrl = "#",
                            Tittle = "Act Now! Get the highest level penthouse"
                        });
                });

            modelBuilder.Entity("VillaAgency.Models.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("ReadDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Contacts", (string)null);
                });

            modelBuilder.Entity("VillaAgency.Models.Entities.FAQ", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("FAQs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d4e5f6a7-4444-4444-4444-000000000001"),
                            Answer = "Get the best villa website template in HTML CSS and Bootstrap for your business. We provide you the best free CSS templates in the world. Please tell your friends about it.",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Question = "Best useful links?"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-4444-4444-4444-000000000002"),
                            Answer = "Dolor almesit amet, consectetur adipiscing elit, sed doesn't eiusmod tempor incididunt ut labore consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsActive = true,
                            IsDeleted = false,
                            Question = "How does this work?"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-4444-4444-4444-000000000003"),
                            Answer = "Dolor almesit amet, consectetur adipiscing elit, sed doesn't eiusmod tempor incididunt ut labore consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsActive = true,
                            IsDeleted = false,
                            Question = "Why is Villa Agency the best?"
                        });
                });

            modelBuilder.Entity("VillaAgency.Models.Entities.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Area")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("int");

                    b.Property<int>("BedRooms")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("Floor")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsContractReady")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Parking")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PaymentProcess")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PropertyTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tittle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("TotalFlatSpace")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("PropertyTypeId");

                    b.ToTable("Properties", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2c3d4e5-2222-2222-2222-000000000001"),
                            Address = "18 Old Street",
                            Area = 545m,
                            Bathrooms = 8,
                            BedRooms = 8,
                            City = "Miami",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A stunning luxury villa located at 18 Old Street Miami. Features 8 bedrooms, 8 bathrooms, and expansive living areas with modern finishes throughout.",
                            Floor = 3,
                            IsActive = true,
                            IsContractReady = true,
                            IsDeleted = false,
                            IsFeatured = true,
                            Parking = "6 spots",
                            PaymentProcess = "Bank",
                            Price = 2264000m,
                            PropertyTypeId = new Guid("a1b2c3d4-1111-1111-1111-000000000001"),
                            State = "OR",
                            Tittle = "Luxury Villa in Miami",
                            TotalFlatSpace = 545m,
                            VideoUrl = "https://youtube.com",
                            ZipCode = "97219"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-2222-2222-2222-000000000002"),
                            Address = "54 New Street",
                            Area = 450m,
                            Bathrooms = 5,
                            BedRooms = 6,
                            City = "Florida",
                            CreatedDate = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A beautiful luxury villa at 54 New Street Florida. Features 6 bedrooms, 5 bathrooms with gorgeous garden views and premium interior design.",
                            Floor = 3,
                            IsActive = true,
                            IsContractReady = true,
                            IsDeleted = false,
                            IsFeatured = true,
                            Parking = "8 spots",
                            PaymentProcess = "Bank",
                            Price = 1180000m,
                            PropertyTypeId = new Guid("a1b2c3d4-1111-1111-1111-000000000001"),
                            State = "OR",
                            Tittle = "Luxury Villa in Florida",
                            TotalFlatSpace = 450m,
                            VideoUrl = "https://youtube.com",
                            ZipCode = "27001"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-2222-2222-2222-000000000003"),
                            Address = "26 Mid Street",
                            Area = 225m,
                            Bathrooms = 4,
                            BedRooms = 5,
                            City = "Portland",
                            CreatedDate = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "An elegant luxury villa at 26 Mid Street Portland. Features 5 bedrooms, 4 bathrooms with a spacious layout and premium finishes.",
                            Floor = 3,
                            IsActive = true,
                            IsContractReady = true,
                            IsDeleted = false,
                            IsFeatured = true,
                            Parking = "10 spots",
                            PaymentProcess = "Bank",
                            Price = 1460000m,
                            PropertyTypeId = new Guid("a1b2c3d4-1111-1111-1111-000000000001"),
                            State = "OR",
                            Tittle = "Luxury Villa in Portland",
                            TotalFlatSpace = 225m,
                            VideoUrl = "https://youtube.com",
                            ZipCode = "38540"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-2222-2222-2222-000000000004"),
                            Address = "12 Hope Street",
                            Area = 125m,
                            Bathrooms = 3,
                            BedRooms = 4,
                            City = "Portland",
                            CreatedDate = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A stylish apartment at 12 Hope Street Portland. Features 4 bedrooms, 3 bathrooms on the 25th floor with amazing city panorama.",
                            Floor = 25,
                            IsActive = true,
                            IsContractReady = true,
                            IsDeleted = false,
                            IsFeatured = false,
                            Parking = "2 cars",
                            PaymentProcess = "Bank",
                            Price = 584500m,
                            PropertyTypeId = new Guid("a1b2c3d4-1111-1111-1111-000000000002"),
                            State = "OR",
                            Tittle = "Modern Apartment in Portland",
                            TotalFlatSpace = 185m,
                            VideoUrl = "https://youtube.com",
                            ZipCode = "12650"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-2222-2222-2222-000000000005"),
                            Address = "34 Hope Street",
                            Area = 180m,
                            Bathrooms = 4,
                            BedRooms = 4,
                            City = "Portland",
                            CreatedDate = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A premium penthouse at 34 Hope Street Portland. Features 4 bedrooms, 4 bathrooms on the 38th floor with stunning skyline views.",
                            Floor = 38,
                            IsActive = true,
                            IsContractReady = true,
                            IsDeleted = false,
                            IsFeatured = false,
                            Parking = "2 cars",
                            PaymentProcess = "Bank",
                            Price = 925600m,
                            PropertyTypeId = new Guid("a1b2c3d4-1111-1111-1111-000000000003"),
                            State = "OR",
                            Tittle = "Premium Penthouse in Portland",
                            TotalFlatSpace = 320m,
                            VideoUrl = "https://youtube.com",
                            ZipCode = "42680"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-2222-2222-2222-000000000006"),
                            Address = "22 Hope Street",
                            Area = 165m,
                            Bathrooms = 2,
                            BedRooms = 3,
                            City = "Portland",
                            CreatedDate = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A contemporary condo at 22 Hope Street Portland. Features 3 bedrooms, 2 bathrooms with smart home technology and modern design.",
                            Floor = 26,
                            IsActive = true,
                            IsContractReady = true,
                            IsDeleted = false,
                            IsFeatured = false,
                            Parking = "3 cars",
                            PaymentProcess = "Bank",
                            Price = 450000m,
                            PropertyTypeId = new Guid("a1b2c3d4-1111-1111-1111-000000000004"),
                            State = "OR",
                            Tittle = "Modern Condo in Portland",
                            TotalFlatSpace = 165m,
                            VideoUrl = "https://youtube.com",
                            ZipCode = "16540"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-2222-2222-2222-000000000007"),
                            Address = "14 Mid Street",
                            Area = 550m,
                            Bathrooms = 8,
                            BedRooms = 8,
                            City = "Miami",
                            CreatedDate = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A grand luxury villa at 14 Mid Street Miami. Features 8 bedrooms, 8 bathrooms with expansive 550m2 living area and private pool.",
                            Floor = 3,
                            IsActive = true,
                            IsContractReady = true,
                            IsDeleted = false,
                            IsFeatured = false,
                            Parking = "12 spots",
                            PaymentProcess = "Bank",
                            Price = 980000m,
                            PropertyTypeId = new Guid("a1b2c3d4-1111-1111-1111-000000000001"),
                            State = "OR",
                            Tittle = "Luxury Villa in Miami Beach",
                            TotalFlatSpace = 550m,
                            VideoUrl = "https://youtube.com",
                            ZipCode = "36450"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-2222-2222-2222-000000000008"),
                            Address = "26 Old Street",
                            Area = 380m,
                            Bathrooms = 15,
                            BedRooms = 12,
                            City = "Miami",
                            CreatedDate = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "An exclusive luxury villa at 26 Old Street Miami. Features 12 bedrooms, 15 bathrooms, offering the ultimate luxury living experience.",
                            Floor = 3,
                            IsActive = true,
                            IsContractReady = true,
                            IsDeleted = false,
                            IsFeatured = false,
                            Parking = "14 spots",
                            PaymentProcess = "Bank",
                            Price = 1520000m,
                            PropertyTypeId = new Guid("a1b2c3d4-1111-1111-1111-000000000001"),
                            State = "OR",
                            Tittle = "Exclusive Villa in Miami",
                            TotalFlatSpace = 380m,
                            VideoUrl = "https://youtube.com",
                            ZipCode = "12870"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-2222-2222-2222-000000000009"),
                            Address = "34 New Street",
                            Area = 860m,
                            Bathrooms = 12,
                            BedRooms = 10,
                            City = "Miami",
                            CreatedDate = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The most prestigious luxury villa at 34 New Street Miami. Features 10 bedrooms, 12 bathrooms with 860m2 of pure elegance.",
                            Floor = 3,
                            IsActive = true,
                            IsContractReady = true,
                            IsDeleted = false,
                            IsFeatured = true,
                            Parking = "10 spots",
                            PaymentProcess = "Bank",
                            Price = 3145000m,
                            PropertyTypeId = new Guid("a1b2c3d4-1111-1111-1111-000000000001"),
                            State = "OR",
                            Tittle = "Grand Villa in Miami",
                            TotalFlatSpace = 860m,
                            VideoUrl = "https://youtube.com",
                            ZipCode = "24650"
                        });
                });

            modelBuilder.Entity("VillaAgency.Models.Entities.PropertyImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyImages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1a1a1a1-0001-0001-0001-000000000001"),
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            ImageUrl = "/assets/images/property-01.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsMain = true,
                            PropertyId = new Guid("b2c3d4e5-2222-2222-2222-000000000001")
                        },
                        new
                        {
                            Id = new Guid("f1a1a1a1-0001-0001-0001-000000000002"),
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            ImageUrl = "/assets/images/property-02.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsMain = true,
                            PropertyId = new Guid("b2c3d4e5-2222-2222-2222-000000000002")
                        },
                        new
                        {
                            Id = new Guid("f1a1a1a1-0001-0001-0001-000000000003"),
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            ImageUrl = "/assets/images/property-03.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsMain = true,
                            PropertyId = new Guid("b2c3d4e5-2222-2222-2222-000000000003")
                        },
                        new
                        {
                            Id = new Guid("f1a1a1a1-0001-0001-0001-000000000004"),
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            ImageUrl = "/assets/images/property-04.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsMain = true,
                            PropertyId = new Guid("b2c3d4e5-2222-2222-2222-000000000004")
                        },
                        new
                        {
                            Id = new Guid("f1a1a1a1-0001-0001-0001-000000000005"),
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            ImageUrl = "/assets/images/property-05.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsMain = true,
                            PropertyId = new Guid("b2c3d4e5-2222-2222-2222-000000000005")
                        },
                        new
                        {
                            Id = new Guid("f1a1a1a1-0001-0001-0001-000000000006"),
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            ImageUrl = "/assets/images/property-06.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsMain = true,
                            PropertyId = new Guid("b2c3d4e5-2222-2222-2222-000000000006")
                        },
                        new
                        {
                            Id = new Guid("f1a1a1a1-0001-0001-0001-000000000007"),
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            ImageUrl = "/assets/images/property-03.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsMain = true,
                            PropertyId = new Guid("b2c3d4e5-2222-2222-2222-000000000007")
                        },
                        new
                        {
                            Id = new Guid("f1a1a1a1-0001-0001-0001-000000000008"),
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            ImageUrl = "/assets/images/property-02.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsMain = true,
                            PropertyId = new Guid("b2c3d4e5-2222-2222-2222-000000000008")
                        },
                        new
                        {
                            Id = new Guid("f1a1a1a1-0001-0001-0001-000000000009"),
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            ImageUrl = "/assets/images/property-01.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsMain = true,
                            PropertyId = new Guid("b2c3d4e5-2222-2222-2222-000000000009")
                        },
                        new
                        {
                            Id = new Guid("f1a1a1a1-0001-0001-0001-000000000010"),
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            ImageUrl = "/assets/images/deal-01.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsMain = false,
                            PropertyId = new Guid("b2c3d4e5-2222-2222-2222-000000000004")
                        },
                        new
                        {
                            Id = new Guid("f1a1a1a1-0001-0001-0001-000000000011"),
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            ImageUrl = "/assets/images/deal-02.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsMain = false,
                            PropertyId = new Guid("b2c3d4e5-2222-2222-2222-000000000002")
                        },
                        new
                        {
                            Id = new Guid("f1a1a1a1-0001-0001-0001-000000000012"),
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            ImageUrl = "/assets/images/deal-03.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsMain = false,
                            PropertyId = new Guid("b2c3d4e5-2222-2222-2222-000000000005")
                        });
                });

            modelBuilder.Entity("VillaAgency.Models.Entities.PropertyType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PropertyTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-1111-1111-1111-000000000001"),
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Premium luxury villas with exclusive designs and amenities.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Luxury Villa"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-1111-1111-1111-000000000002"),
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Modern apartments in prime locations with great city views.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Apartment"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-1111-1111-1111-000000000003"),
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-rise penthouses with panoramic views and top-tier finishes.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Penthouse"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-1111-1111-1111-000000000004"),
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Contemporary condominiums with smart home features.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Modern Condo"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-1111-1111-1111-000000000005"),
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Spacious villa houses with private gardens and pools.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Villa House"
                        });
                });

            modelBuilder.Entity("VillaAgency.Models.Entities.SiteSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MapEmbedUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SiteSettings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e5f6a7b8-5555-5555-5555-000000000001"),
                            Address = "Sunny Isles Beach, FL 33160",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "info@villa.co",
                            IsActive = true,
                            IsDeleted = false,
                            MapEmbedUrl = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d12469.776493332698!2d-80.14036379941481!3d25.907788681148624!2m3!1f357.26927939317244!2f20.870722720054623!3f0!3m2!1i1024!2i768!4f35!3m3!1m2!1s0x88d9add4b4ac788f%3A0xe77469d09480fcdb!2sSunny%20Isles%20Beach!5e1!3m2!1sen!2sth!4v1642869952544!5m2!1sen!2sth",
                            PhoneNumber = "010-020-0340",
                            SiteName = "Villa Agency",
                            VideoUrl = "https://www.youtube.com/watch?v=7HKq20ihNAU"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("VillaAgency.Models.Entities.AppilcationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("VillaAgency.Models.Entities.AppilcationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VillaAgency.Models.Entities.AppilcationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("VillaAgency.Models.Entities.AppilcationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VillaAgency.Models.Entities.Property", b =>
                {
                    b.HasOne("VillaAgency.Models.Entities.PropertyType", "PropertyType")
                        .WithMany("Properties")
                        .HasForeignKey("PropertyTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PropertyType");
                });

            modelBuilder.Entity("VillaAgency.Models.Entities.PropertyImage", b =>
                {
                    b.HasOne("VillaAgency.Models.Entities.Property", "Property")
                        .WithMany("PropertyImages")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("VillaAgency.Models.Entities.Property", b =>
                {
                    b.Navigation("PropertyImages");
                });

            modelBuilder.Entity("VillaAgency.Models.Entities.PropertyType", b =>
                {
                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
